version: "3"
services:
  sonarqube:
    image: sonarqube:lts-community
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    networks:
      - sonar-network

  sonar-scanner:
    image: sonarsource/sonar-scanner-cli
    depends_on:
      - sonarqube
    environment:
      - SONAR_HOST_URL=http://sonarqube:9000
    volumes:
      - .:/usr/src
    command: >
      sonar-scanner
      -Dsonar.projectKey=toolshw
      -Dsonar.sources=.
      -Dsonar.inclusions=hw.py
      -Dsonar.host.url=http://sonarqube:9000
      -Dsonar.login=${SONAR_TOKEN}
    networks:
      - sonar-network
  
networks:
  sonar-network:
